import { FaRegEnvelope } from "react-icons/fa";
import { BsCheck2Circle, BsFillCartFill, BsFillGeoAltFill } from "react-icons/bs";



const Data = {
    AllNewsBlogs:[
        {
            id:1,
            img:"images/blog-img.svg",
            feature:"Featured",
            description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
            titel:"News Title here with long text 2022 with tages of the news.",
            tags:"New Tags 1",
            date:"27-04-2022",
            time:"10:30AM",
            link:"/blogdetails",
        },
        {
            id:2,
            img:"images/blog-img.svg",
            feature:"",
            description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
            titel:"News Title here with long text 2022 with tages of the news.",
            tags:"New Tags 1",
            date:"27-04-2022",
            time:"10:30AM",
            link:"/blogdetails",
        },
        {
            id:3,
            feature:"",
            img:"images/blog-img.svg",
            description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
            titel:"News Title here with long text 2022 with tages of the news.",
            tags:"New Tags 1",
            date:"27-04-2022",
            time:"10:30AM",
            link:"/blogdetails",
        },
        {
            id:4,
            feature:"",
            img:"images/blog-img.svg",
            description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
            titel:"News Title here with long text 2022 with tages of the news.",
            tags:"New Tags 1",
            date:"27-04-2022",
            time:"10:30AM",
            link:"/blogdetails",
        },
        {
            id:5,
            feature:"",
            img:"images/blog-img.svg",
            description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
            titel:"News Title here with long text 2022 with tages of the news.",
            tags:"New Tags 1",
            date:"27-04-2022",
            time:"10:30AM",
            link:"/blogdetails",
        },
        {
            id:6,
            feature:"",
            img:"images/blog-img.svg",
            description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
            titel:"News Title here with long text 2022 with tages of the news.",
            tags:"New Tags 1",
            date:"27-04-2022",
            time:"10:30AM",
            link:"/blogdetails",
        },
        {
            id:7,
            feature:"",
            img:"images/blog-img.svg",
            description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
            titel:"News Title here with long text 2022 with tages of the news.",
            tags:"New Tags 1",
            date:"27-04-2022",
            time:"10:30AM",
            link:"/blogdetails",
        },
        {
            id:8,
            feature:"",
            img:"images/blog-img.svg",
            description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
            titel:"News Title here with long text 2022 with tages of the news.",
            tags:"New Tags 1",
            date:"27-04-2022",
            time:"10:30AM",
            link:"/blogdetails",
        },
        {
            id:9,
            feature:"",
            img:"images/blog-img.svg",
            description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
            titel:"News Title here with long text 2022 with tages of the news.",
            tags:"New Tags 1",
            date:"27-04-2022",
            time:"10:30AM",
            link:"/blogdetails",
        },

        {
            id:10,
            feature:"",
            img:"images/blog-img.svg",
            description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
            titel:"News Title here with long text 2022 with tages of the news.",
            tags:"New Tags 1",
            date:"27-04-2022",
            time:"10:30AM",
            link:"/blogdetails",
        },
        {
            id:11,
            feature:"",
            img:"images/blog-img.svg",
            description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
            titel:"News Title here with long text 2022 with tages of the news.",
            tags:"New Tags 1",
            date:"27-04-2022",
            time:"10:30AM",
            link:"/blogdetails",
        },
        {
            id:12,
            feature:"",
            img:"images/blog-img.svg",
            description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
            titel:"News Title here with long text 2022 with tages of the news.",
            tags:"New Tags 1",
            date:"27-04-2022",
            time:"10:30AM",
            link:"/blogdetails",
        },
     
   
    ],
   
}
export default Data;