import { FaRegEnvelope } from "react-icons/fa";
import { BsCheck2Circle, BsFillCartFill, BsFillGeoAltFill } from "react-icons/bs";



const Data = {
    AllIndustryLogo:[
        {
            id:1,
            img:"images/in-client.svg",
        },
        {
            id:2,
            img:"images/in-client2.svg",
        },
        {
            id:3,
            img:"images/in-client3.svg",
        },
        {
            id:4,
            img:"images/in-client4.svg",
        },
        {
            id:5,
            img:"images/in-client5.svg",
        },
        {
            id:6,
            img:"images/in-client6.png",
        },
        {
            id:7,
            img:"images/in-client7.svg",
        },
        {
            id:8,
            img:"images/in-client8.svg",
        },
        {
            id:9,
            img:"images/in-client9.svg",
        },

        {
            id:10,
            img:"images/in-client10.svg",
        },
        {
            id:11,
            img:"images/in-client11.svg",
        },
        {
            id:12,
            img:"images/in-client12.svg",
        },
        {
            id:13,
            img:"images/in-client13.svg",
        },
        {
            id:14,
            img:"images/in-client14.svg",
        },
        {
            id:15,
            img:"images/in-client15.svg",
        },
        {
            id:16,
            img:"images/in-client16.svg",
        },
        {
            id:17,
            img:"images/in-client17.svg",
        },
        {
            id:18,
            img:"images/in-client18.svg",
        },
        {
            id:19,
            img:"images/in-client19.svg",
        },
        {
            id:20,
            img:"images/in-client20.svg",
        },
        {
            id:21,
            img:"images/in-client21.svg",
        },
        {
            id:22,
            img:"images/in-client22.svg",
        },
        {
            id:23,
            img:"images/in-client23.svg",
        },
        {
            id:24,
            img:"images/in-client24.svg",
        },
    ],
   
}
export default Data;